# Generated by Django 6.0.5 on 2026-05-06 10:09

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('rides', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='ride',
            name='id_driver',
            field=models.ForeignKey(db_column='id_driver', on_delete=django.db.models.deletion.PROTECT, related_name='rides_as_driver', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='ride',
            name='id_rider',
            field=models.ForeignKey(db_column='id_rider', on_delete=django.db.models.deletion.PROTECT, related_name='rides_as_rider', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='rideevent',
            name='id_ride',
            field=models.ForeignKey(db_column='id_ride', on_delete=django.db.models.deletion.CASCADE, related_name='ride_events', to='rides.ride'),
        ),
        migrations.AddIndex(
            model_name='rideevent',
            index=models.Index(fields=['id_ride', 'created_at'], name='idx_ride_event_ride_created'),
        ),
    ]
